Build: Set ISA spec version as 2.2 to support extension zicsr
The upstream bare-metal GCC 12(+) builds the applcation for GD32VF103
series chips failed with the message:
Error: unrecognized opcode `csrrs a5,mstatus,8', extension `zicsr' required

According to the ticket "intexc_gd32vf103.S uses unsupported extension
zicsr on architecture rv32imac" [1], it is due to the version of RISC-V
Unprivileged (formerly User-Level) ISA specification. [2]

This patch sets ISA spec version to 2.2 for GCC 12(+) to fix this issue.

[1]: https://github.com/Nuclei-Software/nuclei-sdk/issues/51
[2]: https://github.com/riscv-collab/riscv-gnu-toolchain#set-default-isa-spec-version